# Generated by Django 3.2.13 on 2023-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('genre_ids', models.CharField(max_length=100)),
            ],
        ),
    ]
