# Generated by Django 3.2.13 on 2023-05-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='like_genres',
            new_name='liked_genres',
        ),
    ]
