# Generated by Django 4.2.1 on 2023-05-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_user_id_article_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
